/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file defines the layout of the 'cb_repo_query_msg' message type.
 */

#ifndef CB_REPO_QUERY_MSG_H
#define CB_REPO_QUERY_MSG_H
#include <message.h>

enum {
  /** The default size of this message type in bytes. */
  CB_REPO_QUERY_MSG_SIZE = 6,

  /** The Active Message type associated with this message. */
  CB_REPO_QUERY_MSG_AM_TYPE = 177,

  /* Field forwarder: type uint8_t, offset (bits) 0, size (bits) 8 */
  /** Offset (in bytes) of the field 'forwarder' */
  CB_REPO_QUERY_MSG_FORWARDER_OFFSET = 0,
  /** Offset (in bits) of the field 'forwarder' */
  CB_REPO_QUERY_MSG_FORWARDER_OFFSETBITS = 0,
  /** Size (in bytes) of the field 'forwarder' */
  CB_REPO_QUERY_MSG_FORWARDER_SIZE = 1,
  /** Size (in bits) of the field 'forwarder' */
  CB_REPO_QUERY_MSG_FORWARDER_SIZEBITS = 8,

  /* Field srcID: type uint16_t, offset (bits) 8, size (bits) 16 */
  /** Offset (in bytes) of the field 'srcID' */
  CB_REPO_QUERY_MSG_SRCID_OFFSET = 1,
  /** Offset (in bits) of the field 'srcID' */
  CB_REPO_QUERY_MSG_SRCID_OFFSETBITS = 8,
  /** Size (in bytes) of the field 'srcID' */
  CB_REPO_QUERY_MSG_SRCID_SIZE = 2,
  /** Size (in bits) of the field 'srcID' */
  CB_REPO_QUERY_MSG_SRCID_SIZEBITS = 16,

  /* Field srcPANID: type uint16_t, offset (bits) 24, size (bits) 16 */
  /** Offset (in bytes) of the field 'srcPANID' */
  CB_REPO_QUERY_MSG_SRCPANID_OFFSET = 3,
  /** Offset (in bits) of the field 'srcPANID' */
  CB_REPO_QUERY_MSG_SRCPANID_OFFSETBITS = 24,
  /** Size (in bytes) of the field 'srcPANID' */
  CB_REPO_QUERY_MSG_SRCPANID_SIZE = 2,
  /** Size (in bits) of the field 'srcPANID' */
  CB_REPO_QUERY_MSG_SRCPANID_SIZEBITS = 16,

  /* Field mode: type uint8_t, offset (bits) 40, size (bits) 8 */
  /** Offset (in bytes) of the field 'mode' */
  CB_REPO_QUERY_MSG_MODE_OFFSET = 5,
  /** Offset (in bits) of the field 'mode' */
  CB_REPO_QUERY_MSG_MODE_OFFSETBITS = 40,
  /** Size (in bytes) of the field 'mode' */
  CB_REPO_QUERY_MSG_MODE_SIZE = 1,
  /** Size (in bits) of the field 'mode' */
  CB_REPO_QUERY_MSG_MODE_SIZEBITS = 8,
};

/**
 * Return the value of the field 'forwarder'
 */
uint8_t cb_repo_query_msg_forwarder_get(tmsg_t *msg);

/**
 * Set the value of the field 'forwarder'
 */
void cb_repo_query_msg_forwarder_set(tmsg_t *msg, uint8_t value);

/**
 * Return the value of the field 'srcID'
 */
uint16_t cb_repo_query_msg_srcID_get(tmsg_t *msg);

/**
 * Set the value of the field 'srcID'
 */
void cb_repo_query_msg_srcID_set(tmsg_t *msg, uint16_t value);

/**
 * Return the value of the field 'srcPANID'
 */
uint16_t cb_repo_query_msg_srcPANID_get(tmsg_t *msg);

/**
 * Set the value of the field 'srcPANID'
 */
void cb_repo_query_msg_srcPANID_set(tmsg_t *msg, uint16_t value);

/**
 * Return the value of the field 'mode'
 */
uint8_t cb_repo_query_msg_mode_get(tmsg_t *msg);

/**
 * Set the value of the field 'mode'
 */
void cb_repo_query_msg_mode_set(tmsg_t *msg, uint8_t value);

#endif
