/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file defines the layout of the 'cb_sweep_data_msg' message type.
 */

#ifndef CB_SWEEP_DATA_MSG_H
#define CB_SWEEP_DATA_MSG_H
#include <message.h>

enum {
  /** The default size of this message type in bytes. */
  CB_SWEEP_DATA_MSG_SIZE = 22,

  /** The Active Message type associated with this message. */
  CB_SWEEP_DATA_MSG_AM_TYPE = 176,

  /* Field src: type uint8_t, offset (bits) 0, size (bits) 8 */
  /** Offset (in bytes) of the field 'src' */
  CB_SWEEP_DATA_MSG_SRC_OFFSET = 0,
  /** Offset (in bits) of the field 'src' */
  CB_SWEEP_DATA_MSG_SRC_OFFSETBITS = 0,
  /** Size (in bytes) of the field 'src' */
  CB_SWEEP_DATA_MSG_SRC_SIZE = 1,
  /** Size (in bits) of the field 'src' */
  CB_SWEEP_DATA_MSG_SRC_SIZEBITS = 8,

  /* Field errorcode: type uint8_t, offset (bits) 8, size (bits) 8 */
  /** Offset (in bytes) of the field 'errorcode' */
  CB_SWEEP_DATA_MSG_ERRORCODE_OFFSET = 1,
  /** Offset (in bits) of the field 'errorcode' */
  CB_SWEEP_DATA_MSG_ERRORCODE_OFFSETBITS = 8,
  /** Size (in bytes) of the field 'errorcode' */
  CB_SWEEP_DATA_MSG_ERRORCODE_SIZE = 1,
  /** Size (in bits) of the field 'errorcode' */
  CB_SWEEP_DATA_MSG_ERRORCODE_SIZEBITS = 8,

  /* Field seqno: type uint32_t, offset (bits) 16, size (bits) 32 */
  /** Offset (in bytes) of the field 'seqno' */
  CB_SWEEP_DATA_MSG_SEQNO_OFFSET = 2,
  /** Offset (in bits) of the field 'seqno' */
  CB_SWEEP_DATA_MSG_SEQNO_OFFSETBITS = 16,
  /** Size (in bytes) of the field 'seqno' */
  CB_SWEEP_DATA_MSG_SEQNO_SIZE = 4,
  /** Size (in bits) of the field 'seqno' */
  CB_SWEEP_DATA_MSG_SEQNO_SIZEBITS = 32,

  /* Field rssi: type int8_t[], element size (bits) 8 */
  /** Elementsize (in bytes) of the field 'rssi' */
  CB_SWEEP_DATA_MSG_RSSI_ELEMENTSIZE = 1,
  /** Elementsize (in bits) of the field 'rssi' */
  CB_SWEEP_DATA_MSG_RSSI_ELEMENTSIZEBITS = 8,
  /** The number of dimensions in the array 'rssi'. */
  CB_SWEEP_DATA_MSG_RSSI_NUMDIMENSIONS = 1,
  /** Number of elements in dimension 1 of array 'rssi'. */
  CB_SWEEP_DATA_MSG_RSSI_NUMELEMENTS_1 = 16,
  /** Total number of elements in the array 'rssi'. */
  CB_SWEEP_DATA_MSG_RSSI_NUMELEMENTS = 16,
};

/**
 * Return the value of the field 'src'
 */
uint8_t cb_sweep_data_msg_src_get(tmsg_t *msg);

/**
 * Set the value of the field 'src'
 */
void cb_sweep_data_msg_src_set(tmsg_t *msg, uint8_t value);

/**
 * Return the value of the field 'errorcode'
 */
uint8_t cb_sweep_data_msg_errorcode_get(tmsg_t *msg);

/**
 * Set the value of the field 'errorcode'
 */
void cb_sweep_data_msg_errorcode_set(tmsg_t *msg, uint8_t value);

/**
 * Return the value of the field 'seqno'
 */
uint32_t cb_sweep_data_msg_seqno_get(tmsg_t *msg);

/**
 * Set the value of the field 'seqno'
 */
void cb_sweep_data_msg_seqno_set(tmsg_t *msg, uint32_t value);

/**
 * Return the byte offset of an element of array 'rssi'
 */
size_t cb_sweep_data_msg_rssi_offset(size_t index1);

/**
 * Return an element of the array 'rssi'
 */
int8_t cb_sweep_data_msg_rssi_get(tmsg_t *msg, size_t index1);

/**
 * Set an element of the array 'rssi'
 */
void cb_sweep_data_msg_rssi_set(tmsg_t *msg, size_t index1, int8_t value);

/**
 * Return the bit offset of an element of array 'rssi'
 */
size_t cb_sweep_data_msg_rssi_offsetbits(size_t index1);

#endif
