/**
 * This file is automatically generated by mig. DO NOT EDIT THIS FILE.
 * This file implements the functions for encoding and decoding the
 * 'cb_sweep_data_msg' message type. See CBSweepDataMsg.h for more details.
 */

#include <message.h>
#include "CBSweepDataMsg.h"

uint8_t cb_sweep_data_msg_src_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 0, 8);
}

void cb_sweep_data_msg_src_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 0, 8, value);
}

uint8_t cb_sweep_data_msg_errorcode_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 8, 8);
}

void cb_sweep_data_msg_errorcode_set(tmsg_t *msg, uint8_t value)
{
  tmsg_write_ube(msg, 8, 8, value);
}

uint32_t cb_sweep_data_msg_seqno_get(tmsg_t *msg)
{
  return tmsg_read_ube(msg, 16, 32);
}

void cb_sweep_data_msg_seqno_set(tmsg_t *msg, uint32_t value)
{
  tmsg_write_ube(msg, 16, 32, value);
}

size_t cb_sweep_data_msg_rssi_offset(size_t index1)
{
  return cb_sweep_data_msg_rssi_offsetbits(index1) / 8;
}

int8_t cb_sweep_data_msg_rssi_get(tmsg_t *msg, size_t index1)
{
  return tmsg_read_be(msg, cb_sweep_data_msg_rssi_offsetbits(index1), 8);
}

void cb_sweep_data_msg_rssi_set(tmsg_t *msg, size_t index1, int8_t value)
{
  tmsg_write_be(msg, cb_sweep_data_msg_rssi_offsetbits(index1), 8, value);
}

size_t cb_sweep_data_msg_rssi_offsetbits(size_t index1)
{
  size_t offset = 48;
  if (index1 >= 16) { tmsg_fail(); return (size_t)-1; }
  offset += 0 + index1 * 8;
  return offset;
}

